name: Build and Package .ipa
on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  build-ipa:
   # Use the latest available macOS runner
    runs-on: macos-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Select latest Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Install iOS 18.1 Simulator Runtime
        run: |
          curl -L -o iOS18.1.dmg "https://devimages-cdn.apple.com/downloads/Xcode_16/Xcode_16.app/Contents/Resources/Runtimes/iOS 18.1.simruntime.dmg"
          hdiutil attach iOS18.1.dmg
          cp -R "/Volumes/iOS 18.1 simruntime/iOS 18.1.simruntime" "/Library/Developer/CoreSimulator/Profiles/Runtimes/"
          hdiutil detach "/Volumes/iOS 18.1 simruntime"

      - name: Resolve SPM dependencies
        run: xcodebuild -resolvePackageDependencies -project winston.xcodeproj -scheme winston

      - name: Build Archive
        run: |
          xcodebuild -project winston.xcodeproj \
                     -scheme winston \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     -archivePath $RUNNER_TEMP/winston.xcarchive \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     archive

      - name: Create .ipa file
        run: |
          mkdir -p $RUNNER_TEMP/Payload
          cp -R $RUNNER_TEMP/winston.xcarchive/Products/Applications/winston.app $RUNNER_TEMP/Payload/winston.app
          cd $RUNNER_TEMP
          zip -r winston.ipa ./Payload

      - name: Upload .ipa Artifact
      # This action uploads the generated .ipa as a workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: winston-ipa
          path: ${{ runner.temp }}/winston.ipa
          retention-days: 7
